site_name: "de.NBI Cloud Wiki"
docs_dir: wiki
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'cyan'
  logo: 'img/SimpleVM_logo_wiki.svg'
  favicon: 'img/simplevm_favicon.svg'
  features:
    - content.code.copy

repo_name: 'deNBI/simplevm-user-docs'
repo_url: 'https://github.com/deNBI/simplevm-user-docs'
edit_uri: blob/master/wiki/
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - toc: 
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.blocks.caption
nav:
  - 'Home' : index.md
  - 'Group Permissions': simple_vm/permissions.md
  - 'Project Management': simple_vm/projects.md
  - 'VM Management':
    - simple_vm/Instance/index.md
    - 'Create Instance': simple_vm/Instance/create_instance.md
    - 'Instance overview': simple_vm/Instance/instance_overview.md
    - 'Instance details': simple_vm/Instance/instance_detail.md
  - 'Cluster Management' :
    - simple_vm/Cluster/index.md
    - 'New cluster': simple_vm/Cluster/new_cluster.md
    - 'Cluster overview': simple_vm/Cluster/cluster_overview.md
    - 'Cluster detail': simple_vm/Cluster/cluster_detail.md
  - 'SSH keys and sharing access': simple_vm/keypairs.md
  - 'User API keys': simple_vm/userapikeys.md
  - 'Volumes': simple_vm/volumes.md
  - 'Images/Snapshots': simple_vm/snapshots.md
  - 'Backuping data': simple_vm/backup.md
  - 'Customization': simple_vm/customization.md
  - 'Concurrent Guacamole sessions': simple_vm/guacamole.md
  - 'Concurrent RStudio sessions': simple_vm/rstudio.md
  - 'Workshops': simple_vm/workshop.md
  - 'Miscellaneous': simple_vm/misc.md
  - 'Tutorials' :
    - 'Tutorials': Tutorials/index.md
    - 'Access a SimpleVM with Mosh' : Tutorials/Mosh/index.md
    - 'SimpleVM File Transfer' : Tutorials/File_Transfer_Methods/index.md
  - 'FAQ' : 'FAQ.md'