site_name: "de.NBI Cloud Wiki"
docs_dir: wiki
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'cyan'
  logo: 'img/SimpleVM_New.svg'
  favicon: 'img/simplevm_favicon.svg'
repo_name: 'deNBI/simplevm-user-docs'
repo_url: 'https://github.com/deNBI/simplevm-user-docs'
edit_uri: blob/master/wiki/
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 'Home' : index.md
  - 'Simple VM':
      - 'Group Permissions': simple_vm/permissions.md
      - 'New instance': simple_vm/new_instance.md
      - 'Instance overview': simple_vm/instance_overview.md
      - 'Instance details': simple_vm/instance_detail.md
      - 'Cluster' :
        - 'Cluster': simple_vm/Cluster/index.md
        - 'New cluster': simple_vm/Cluster/new_cluster.md
        - 'Cluster overview': simple_vm/Cluster/cluster_overview.md
      - 'SSH keys and sharing access': simple_vm/keypairs.md
      - 'Volumes': simple_vm/volumes.md
      - 'Images/Snapshots': simple_vm/snapshots.md
      - 'Backuping data': simple_vm/backup.md
      - 'Customization': simple_vm/customization.md
      - 'Concurrent Guacamole sessions': simple_vm/guacamole.md
      - 'Concurrent RStudio sessions': simple_vm/rstudio.md
      - 'Workshops': simple_vm/workshop.md
      - 'Miscellaneous': simple_vm/misc.md
  - 'Tutorials' :
    - 'Access de.NBI Virtual Machines from Windows 10' : Tutorials/Win10_SSH/index.md
    - 'Access a SimpleVM with Mosh' : Tutorials/Mosh/index.md
    - 'Bibigrid' : Tutorials/BiBiGrid/index.md
    - 'Blast on BiBiGrid' : Tutorials/BlastOnBiBiGrid/index.md
    - 'Install latest CUDA version' : Tutorials/CUDA/index.md
    - 'Persistent SSH Sessions' : Tutorials/Persistent_SSH_Sessions/index.md
    - 'SimpleVM File Transfer' : Tutorials/File_Transfer_Methods/index.md
    - 'UserData' : Tutorials/UserData/index.md
  - 'FAQ' : 'FAQ.md'
  - 'Compute Center Specific' :
    - 'Giessen' : Compute_Center/Giessen.md
    - 'Bielefeld' : Compute_Center/Bielefeld.md
    - 'Heidelberg Uni' : Compute_Center/Heidelberg.md
    - 'Heidelberg DKFZ' : Compute_Center/Heidelberg-DKFZ.md
    - 'Tuebingen' : Compute_Center/Tuebingen.md
    - 'Freiburg' : Compute_Center/Freiburg.md
    - 'Berlin' : Compute_Center/Berlin.md
    - 'EMBL' : Compute_Center/EMBL.md
  - 'Cloud Admin':
    - 'Configure OpenStack to use Elixir AAI via OpenID Connect': cloud_admin/elixir_OIDC.md
    - 'Register your identity provider for ELIXIR': cloud_admin/identity_provider.md
    - 'News management': cloud_admin/news_management.md
    - 'Vault management': cloud_admin/vault_admin.md
